# Generated by Django 3.1.3 on 2021-01-23 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20210123_1715'),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('subtitle', models.CharField(max_length=150)),
                ('desсription', models.TextField(max_length=300)),
                ('price', models.IntegerField()),
                ('genre', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('year', models.DateField()),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='todo',
            name='is_closed',
            field=models.NullBooleanField(default=True),
        ),
    ]
