# Generated by Django 3.1.3 on 2021-01-23 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20210123_2255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='date',
        ),
        migrations.AlterField(
            model_name='books',
            name='desсription',
            field=models.CharField(max_length=30),
        ),
    ]
