# Generated by Django 3.1.3 on 2021-01-24 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20210124_0045'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Books',
        ),
    ]
